package v3

// Match input indicates that matching should be done on the response status
// code.
#HttpResponseStatusCodeMatchInput: {
	"@type": "type.googleapis.com/envoy.type.matcher.v3.HttpResponseStatusCodeMatchInput"
}

// Match input indicates that the matching should be done on the class of the
// response status code. For eg: 1xx, 2xx, 3xx, 4xx or 5xx.
#HttpResponseStatusCodeClassMatchInput: {
	"@type": "type.googleapis.com/envoy.type.matcher.v3.HttpResponseStatusCodeClassMatchInput"
}

// This match input determines whether the response is a local reply which gets
// generated by Envoy or a response from the upstream.
//
// The input string is “true“ for local replies and “false“ for the upstream
// responses.
//
// It can be used with the “custom_response“ filter to apply policies only to
// the Envoy generated local replies.
// [#extension: envoy.matching.inputs.local_reply]
#HttpResponseLocalReplyMatchInput: {
	"@type": "type.googleapis.com/envoy.type.matcher.v3.HttpResponseLocalReplyMatchInput"
}
